groups:
  - name: example-alerts
    rules:
      - alert: HighRequestRate
        expr: rate(http_server_requests_seconds_count[1m]) > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High request rate detected"
          description: "Service {{ $labels.job }} has >5 requests/sec"