global:
  scrape_interval: 5s   # How often to scrape targets

scrape_configs:
  - job_name: 'product-mdm-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-product-mdm:8080']
        labels : 
           env : dev
           service : product
  - job_name: 'customer-mdm-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-customer-mdm:8080']
        labels : 
           env : dev
           service : customer
  - job_name: 'order-sales-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-order-sales:8080']
        labels : 
           env : dev
           service : order
rule_files:
  - "alert_rules.yml"
